# Generated by Django 3.1.6 on 2021-06-30 07:49

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvroTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bool_field', models.BooleanField(default=False, null=True)),
                ('char_field', models.CharField(default='', max_length=255, null=True)),
                ('date_field', models.DateField(default=django.utils.timezone.now, null=True)),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('float_field', models.FloatField(default=0.0, null=True)),
                ('int_field', models.IntegerField(default=0, null=True)),
                ('integerrange_field', django.contrib.postgres.fields.ranges.IntegerRangeField(default=None, null=True)),
                ('datetimerange_field', django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None, null=True)),
                ('file_field', models.FileField(default=None, null=True, upload_to='')),
                ('text_field', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvroTest0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvroTest3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('fk_avrotest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avrotest3', to='django_avroserializer.avrotest')),
            ],
        ),
        migrations.CreateModel(
            name='AvroTest4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('avrotest3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avrotest4_obj', to='django_avroserializer.avrotest3')),
            ],
        ),
        migrations.CreateModel(
            name='AvroTest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('avrotests', models.ManyToManyField(related_name='avrotest2s', to='django_avroserializer.AvroTest')),
            ],
        ),
        migrations.AddField(
            model_name='avrotest',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avro_tests', to='django_avroserializer.avrotest0'),
        ),
        migrations.AddField(
            model_name='avrotest',
            name='m2m',
            field=models.ManyToManyField(related_name='_avrotest_m2m_+', to='django_avroserializer.AvroTest'),
        ),
        migrations.AddField(
            model_name='avrotest',
            name='m2m_avrotest0',
            field=models.ManyToManyField(related_name='m2m_avrotests', to='django_avroserializer.AvroTest0'),
        ),
    ]
