# Generated by Django 3.1.6 on 2021-06-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_avroserializer', '0002_auto_20210630_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avrotest4',
            name='avrotest3',
        ),
        migrations.AddField(
            model_name='avrotest4',
            name='avrotest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avrotest4_121', to='django_avroserializer.avrotest'),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_avrotests', to='django_avroserializer.avrotest0'),
        ),
        migrations.AlterField(
            model_name='avrotest2',
            name='avrotests',
            field=models.ManyToManyField(related_name='m2m_avrotest2s', to='django_avroserializer.AvroTest'),
        ),
        migrations.AlterField(
            model_name='avrotest3',
            name='fk_avrotest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_avrotest3s', to='django_avroserializer.avrotest'),
        ),
    ]
