# Generated by Django 3.1.6 on 2021-07-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_avroserializer', '0003_auto_20210630_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avrotest2',
            name='avrotests',
        ),
        migrations.RemoveField(
            model_name='avrotest3',
            name='fk_avrotest',
        ),
        migrations.RemoveField(
            model_name='avrotest4',
            name='avrotest',
        ),
        migrations.DeleteModel(
            name='AvroTest',
        ),
        migrations.DeleteModel(
            name='AvroTest0',
        ),
        migrations.DeleteModel(
            name='AvroTest2',
        ),
        migrations.DeleteModel(
            name='AvroTest3',
        ),
        migrations.DeleteModel(
            name='AvroTest4',
        ),
    ]
