# Generated by Django 3.1.6 on 2021-06-01 09:38

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameRangeId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('frames', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('temporal', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('x_centre', models.FloatField()),
                ('y_centre', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YasnaAnnotation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YasnaObject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='yasnaobject',
            index=models.Index(fields=['id'], name='yasna_yasna_id_791ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='yasnaobject',
            index=models.Index(fields=['label'], name='yasna_yasna_label_b6363f_idx'),
        ),
        migrations.AddField(
            model_name='yasnaannotation',
            name='framez',
            field=models.ManyToManyField(related_name='annotations', to='yasna.FrameRangeId'),
        ),
        migrations.AddField(
            model_name='trackedid',
            name='framez',
            field=models.ManyToManyField(related_name='boxes', to='yasna.FrameRangeId'),
        ),
        migrations.AddField(
            model_name='trackedid',
            name='yasnaobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectboundingbox', to='yasna.yasnaobject'),
        ),
    ]
