# Generated by Django 3.1.6 on 2021-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='yasnaannotation',
            index=models.Index(fields=['type'], name='yasna_yasna_type_125071_idx'),
        ),
        migrations.AddIndex(
            model_name='yasnaannotation',
            index=models.Index(fields=['label'], name='yasna_yasna_label_5cac1f_idx'),
        ),
    ]
