# Generated by Django 3.1.6 on 2021-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0002_auto_20210601_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='yasnaobject',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='cross_references',
            field=models.ManyToManyField(related_name='_yasnaobject_cross_references_+', to='yasna.YasnaObject'),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='definition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='description_of_action',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='function',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='interpretation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='name_in_avestan',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='name_in_gujarati',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='name_in_middle_persian',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='references',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='translation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yasnaobject',
            name='where_during_ritual',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='yasnaobject',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
