# Generated by Django 3.1.6 on 2021-06-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0003_auto_20210602_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='YasnaObjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, upload_to=None)),
                ('yasna_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yasna.yasnaobject')),
            ],
        ),
    ]
