# Generated by Django 3.1.6 on 2021-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0004_yasnaobjectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='yasnaobjectimage',
            name='seq_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yasnaobjectimage',
            name='image',
            field=models.FileField(max_length=255, upload_to='yasna_object_images/'),
        ),
    ]
