# Generated by Django 3.1.6 on 2021-06-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0005_auto_20210607_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yasnaobject',
            options={'ordering': ['id']},
        ),
    ]
