# Generated by Django 3.1.6 on 2021-06-16 15:35

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0007_auto_20210609_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameRangeIdTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('frames', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('temporal', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
            ],
        ),
    ]
