# Generated by Django 3.1.6 on 2021-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0008_framerangeidtemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvroTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('char_field', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
