# Generated by Django 3.1.6 on 2021-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0009_avrotest'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='float_field',
            field=models.FloatField(default=0.0),
        ),
    ]
