# Generated by Django 3.1.6 on 2021-06-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0010_avrotest_float_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='bool_field',
            field=models.BooleanField(default=False),
        ),
    ]
