# Generated by Django 3.1.6 on 2021-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0011_avrotest_bool_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='m2m',
            field=models.ManyToManyField(related_name='_avrotest_m2m_+', to='yasna.AvroTest'),
        ),
    ]
