# Generated by Django 3.1.6 on 2021-06-17 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0012_avrotest_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='date_field',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 15, 5, 11, 727737, tzinfo=utc)),
        ),
    ]
