# Generated by Django 3.1.6 on 2021-06-17 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0013_avrotest_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
