# Generated by Django 3.1.6 on 2021-06-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0014_auto_20210617_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameRangeIdTemp',
        ),
    ]
