# Generated by Django 3.1.6 on 2021-06-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0015_delete_framerangeidtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avro_tests', to='yasna.yasnaobject'),
        ),
    ]
