# Generated by Django 3.1.6 on 2021-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0016_avrotest_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='int_field',
            field=models.IntegerField(default=0),
        ),
    ]
