# Generated by Django 3.1.6 on 2021-06-17 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0017_avrotest_int_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avrotest',
            name='bool_field',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='char_field',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='float_field',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='avrotest',
            name='int_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
