# Generated by Django 3.1.6 on 2021-06-19 03:57

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0018_auto_20210617_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='integerrange_field',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=None, null=True),
        ),
    ]
