# Generated by Django 3.1.6 on 2021-06-28 15:18

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0019_avrotest_integerrange_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='datetimerange_field',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None, null=True),
        ),
    ]
