# Generated by Django 3.1.6 on 2021-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0020_avrotest_datetimerange_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvroTest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('avrotests', models.ManyToManyField(related_name='avrotest2s', to='yasna.AvroTest')),
            ],
        ),
    ]
