# Generated by Django 3.1.6 on 2021-06-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0022_avrotest_m2m_yasna_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvroTest3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('fk_avrotest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avrotest3', to='yasna.avrotest')),
            ],
        ),
    ]
