# Generated by Django 3.1.6 on 2021-06-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0023_avrotest3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvroTest4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, null=True)),
                ('yasna_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avrotest4_obj', to='yasna.yasnaobject')),
            ],
        ),
    ]
