# Generated by Django 3.1.6 on 2021-06-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0025_auto_20210629_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrotest',
            name='file_field',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='avrotest',
            name='text_field',
            field=models.TextField(default=None, null=True),
        ),
    ]
