# Generated by Django 3.1.6 on 2021-06-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0026_auto_20210630_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avrotest2',
            name='avrotests',
        ),
        migrations.RemoveField(
            model_name='avrotest3',
            name='fk_avrotest',
        ),
        migrations.RemoveField(
            model_name='avrotest4',
            name='yasna_object',
        ),
        migrations.DeleteModel(
            name='AvroTest',
        ),
        migrations.DeleteModel(
            name='AvroTest2',
        ),
        migrations.DeleteModel(
            name='AvroTest3',
        ),
        migrations.DeleteModel(
            name='AvroTest4',
        ),
    ]
