# Generated by Django 3.1.6 on 2021-11-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0027_auto_20210630_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yasnaobject',
            name='cross_references',
            field=models.ManyToManyField(to='yasna.YasnaObject'),
        ),
    ]
