# Generated by Django 3.1.6 on 2021-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0028_auto_20211101_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='yasnaobject',
            name='collaborator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
