# Generated by Django 3.1.6 on 2021-11-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasna', '0029_yasnaobject_collaborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yasnaobject',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='yasnaobject',
            name='translation',
        ),
    ]
