name: Jest Unit Tests
on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./yasna_frontend
        run: yarn
      - name: Run tests
        working-directory: ./yasna_frontend
        run: yarn test
